In [1]:
import numpy as np
import pandas as pd

# Series

*   한가지 타입의 값 여러개를 저장하는 1차원 모양의 데이터 타입(클래스)
*   축(axis) 레이블을 가지고 있는 1차원 배열(ndarray)
    *   정수 기반의 인덱스와 축 레이블을 함께 가질 수 있음.

In [2]:
s= pd.Series([1, 2, -3, -4, 5])

In [3]:
type(s)

pandas.core.series.Series

In [4]:
print(type(s))

<class 'pandas.core.series.Series'>

In [5]:
print(s)

0    1
1    2
2   -3
3   -4
4    5
dtype: int64

In [6]:
s

0    1
1    2
2   -3
3   -4
4    5
dtype: int64

In [7]:
s.index  # Series 객체의 index 속성

RangeIndex(start=0, stop=5, step=1)

In [8]:
s.values # Series 객체의 values 속성

array([ 1,  2, -3, -4,  5])

## indexing, slicing

*   `iloc`: ndarray에서 자동으로 부여되는 정수 인덱스 기반으로 원소를
참조.   
    *   list 또는 ndarray에서 사용하는 방법과 같음.
    *   **음수 인덱스 사용이 가능.** (마지막 원소부터 역순으로 자동 부여되는) index =i
*   `loc` : 축 레이블을 기반으로 원소를 참조.
    *   **음수 인덱스 사용이 불가능.**  label =l

In [9]:
s.iloc[0] # 시리즈의 첫번째 원소

np.int64(1)

In [10]:
s.iloc[-1]

np.int64(5)

In [11]:
s.iloc[:2] # 시리즈에서 첫(앞) 2개 원소 잘라내기

0    1
1    2
dtype: int64

In [12]:
s.iloc[-2:] # 시리즈에서 마지막 2개 원소 잘라내기

3   -4
4    5
dtype: int64

In [13]:
s.iloc[3:5]

3   -4
4    5
dtype: int64

In [14]:
s.loc[0]

np.int64(1)

In [15]:
s.loc[4]

np.int64(5)

In [16]:
# s.loc[-1] # 음수불가 list나 ndarray처럼 끝에서부터 역순으로 부여되는 음수 인덱스는 없음.

In [17]:
s.loc[0:2] # 0<=x<=2

0    1
1    2
2   -3
dtype: int64

In [18]:
s.loc[3:4]

3   -4
4    5
dtype: int64

In [19]:
s = pd.Series(data=[1,2,-3,-4,5], index=['a','b','x','y','z'])

In [20]:
s

a    1
b    2
x   -3
y   -4
z    5
dtype: int64

In [21]:
s.index

Index(['a', 'b', 'x', 'y', 'z'], dtype='object')

In [22]:
s.values

array([ 1,  2, -3, -4,  5])

In [23]:
s.iloc[0]

np.int64(1)

In [24]:
s.iloc[-1]

np.int64(5)

In [25]:
s.iloc[0:2]

a    1
b    2
dtype: int64

In [26]:
s.iloc[-2:]

y   -4
z    5
dtype: int64

In [27]:
s.loc['a'] #인덱스 번호 변경되어서

np.int64(1)

In [28]:
s.loc['z']

np.int64(5)

In [29]:
s.loc['a':'b']

a    1
b    2
dtype: int64

## fancy indexing

iloc와 loc에서 모두 사용 가능.

In [30]:
s

a    1
b    2
x   -3
y   -4
z    5
dtype: int64

In [31]:
s.loc[['a','x','z']] # 원하는거 검색 가능 단 정해져있는 인덱스값으로

a    1
x   -3
z    5
dtype: int64

In [32]:
s.iloc[[0,4]] # 정수로 원하는거 검색 가능

a    1
z    5
dtype: int64

##boolean indexing

loc만 사용가능, iloc는 사용불가

In [33]:
s.loc[[True, True, False, False, True]] #트루위치의 값만 뽑아냄

a    1
b    2
z    5
dtype: int64

In [34]:
s>0  # element-wise(원소별) 연산수행.

a     True
b     True
x    False
y    False
z     True
dtype: bool

In [35]:
s.loc[s>0] #core

a    1
b    2
z    5
dtype: int64

In [36]:
s.loc[s<0] #core

x   -3
y   -4
dtype: int64

# DataFrame

*   테이블 모양의 2차원 데이터 타입.
    *   행(row)과 열(column)을 가지고 있는 데이터 타입.

In [37]:
data = {
    'city':['서울']*3+['경기도']*3,
    'year':[2022,2023,2024]*2,
    'pop':[0.89,0.91,0.92,1.1,1.2,1.15]
}
data

{'city': ['서울', '서울', '서울', '경기도', '경기도', '경기도'],
 'year': [2022, 2023, 2024, 2022, 2023, 2024],
 'pop': [0.89, 0.91, 0.92, 1.1, 1.2, 1.15]}

In [38]:
df= pd.DataFrame(data)

In [39]:
print(df)

  city  year   pop
0   서울  2022  0.89
1   서울  2023  0.91
2   서울  2024  0.92
3  경기도  2022  1.10
4  경기도  2023  1.20
5  경기도  2024  1.15

In [40]:
df

  city  year   pop
0   서울  2022  0.89
1   서울  2023  0.91
2   서울  2024  0.92
3  경기도  2022  1.10
4  경기도  2023  1.20
5  경기도  2024  1.15

## DataFrame의 속성들

In [41]:
print('shape: ',df.shape)  #shape: (row 개수, column 개수)

shape:  (6, 3)

In [42]:
print('index: ',df.index)  #index: 행 레이블(row label).

index:  RangeIndex(start=0, stop=6, step=1)

In [43]:
print('columns: ',df.columns)  #columns: 컬럼 레이블(column label)

columns:  Index(['city', 'year', 'pop'], dtype='object')

In [44]:
print(df.values)  #values: 데이터프레임의 값들로만 만들어진 2차원 ndarray

[['서울' 2022 0.89]
 ['서울' 2023 0.91]
 ['서울' 2024 0.92]
 ['경기도' 2022 1.1]
 ['경기도' 2023 1.2]
 ['경기도' 2024 1.15]]

## DataFrame에서 column 선택하는 방법

*   `data_frame['column_index(name)']`
    *   항상 사용이 가능하다.
*   `data_frame.column_name`
    *   컬럼의 이름이 변수 이름 규칙에 맞지 않는 경우에는 사용할 수 없음.
        *   변수 이름은 영문자, 숫자, _(underscore)만 사용 가능.
        *   변수 이름은 숫자로 시작할 수 없음.
        *   파이썬 키워드(if, for, while, def, class, ...)들은 변수 이름으로 사용할 수 없음.
    *   컬럼 이름이 DataFrame 클래스의 속성 또는 메서드 이름과 같은 경우에는 사용할 수 없음.

In [45]:
df['city']

0     서울
1     서울
2     서울
3    경기도
4    경기도
5    경기도
Name: city, dtype: object

In [46]:
df.city

0     서울
1     서울
2     서울
3    경기도
4    경기도
5    경기도
Name: city, dtype: object

In [47]:
df['pop']

0    0.89
1    0.91
2    0.92
3    1.10
4    1.20
5    1.15
Name: pop, dtype: float64

In [48]:
df.pop # DataFrame에서 정의된 pop 메서드 객체.

<bound method DataFrame.pop of   city  year   pop
0   서울  2022  0.89
1   서울  2023  0.91
2   서울  2024  0.92
3  경기도  2022  1.10
4  경기도  2023  1.20
5  경기도  2024  1.15>

In [49]:
# 2개 이상의 컬럼을 함께 선택
# select city, pop from df;
df[['city','pop']]

  city   pop
0   서울  0.89
1   서울  0.91
2   서울  0.92
3  경기도  1.10
4  경기도  1.20
5  경기도  1.15

In [50]:
df[['year','pop','city']]

   year   pop city
0  2022  0.89   서울
1  2023  0.91   서울
2  2024  0.92   서울
3  2022  1.10  경기도
4  2023  1.20  경기도
5  2024  1.15  경기도

## DataFrame에서 row 선택 방법

*   `data_frame.iloc[idx]` : 배열(ndarray)의 정수 인덱스를 사용해서 행을 선택.
*   `data_frame.loc[idx]`  : DataFrame의 index속성(row label)을 사용해서 행을 선택.

In [51]:
df

  city  year   pop
0   서울  2022  0.89
1   서울  2023  0.91
2   서울  2024  0.92
3  경기도  2022  1.10
4  경기도  2023  1.20
5  경기도  2024  1.15

In [52]:
df.iloc[0] #첫

city      서울
year    2022
pop     0.89
Name: 0, dtype: object

In [53]:
df.iloc[-1] #마지막

city     경기도
year    2024
pop     1.15
Name: 5, dtype: object

In [54]:
df.loc[5]  #df.loc[-1] Error

city     경기도
year    2024
pop     1.15
Name: 5, dtype: object

In [55]:
df.iloc[:3] #데이터프레임에서 첫 3개 행

  city  year   pop
0   서울  2022  0.89
1   서울  2023  0.91
2   서울  2024  0.92

In [56]:
df.loc[:2] #

  city  year   pop
0   서울  2022  0.89
1   서울  2023  0.91
2   서울  2024  0.92

In [57]:
df.iloc[-3:] #데이터프레임에서 마지막 3개 행

  city  year   pop
3  경기도  2022  1.10
4  경기도  2023  1.20
5  경기도  2024  1.15

In [58]:
df.loc[3:6] #[3:]

  city  year   pop
3  경기도  2022  1.10
4  경기도  2023  1.20
5  경기도  2024  1.15

### fancy indexing

In [59]:
df.iloc[[0,2,4]]

  city  year   pop
0   서울  2022  0.89
2   서울  2024  0.92
4  경기도  2023  1.20

In [60]:
df.loc[[0,2,4]]

  city  year   pop
0   서울  2022  0.89
2   서울  2024  0.92
4  경기도  2023  1.20

### boolean indexing

*   조건을 만족하는 행(row)들을 선택하는 방법.
*   `iloc`는 사용할 수 없음.
*   `data_frame.loc[조건식]` 또는 `data_frame[조건식]`

In [61]:
df.loc[[True, True, False,False,True,False]] # iloc도 가능 boolean에서는불가

  city  year   pop
0   서울  2022  0.89
1   서울  2023  0.91
4  경기도  2023  1.20

In [62]:
df.city == '서울' # 비교연산

0     True
1     True
2     True
3    False
4    False
5    False
Name: city, dtype: bool

In [63]:
df.loc[df.city=='서울'] #True인 값 출력

  city  year   pop
0   서울  2022  0.89
1   서울  2023  0.91
2   서울  2024  0.92

In [64]:
df[df.city=='서울']

  city  year   pop
0   서울  2022  0.89
1   서울  2023  0.91
2   서울  2024  0.92

In [65]:
# 2024년 행만 선택
df[df.year==2024]

  city  year   pop
2   서울  2024  0.92
5  경기도  2024  1.15

*   boolean indexing에서는 파이썬 논리 연산자 키워드`and,or,not`을 사용할 수 없음.
*   대신에 `&, |, ~`연산자를 사용함.
*   `&, |`의 피연산자들은 반드시`()`를 사용해야 함.

In [66]:
# year 컬럼의 값이 2023 또는 2024인 행을 선택.
df[(df.year==2023)|(df.year==2024)] # or (X)

  city  year   pop
1   서울  2023  0.91
2   서울  2024  0.92
4  경기도  2023  1.20
5  경기도  2024  1.15

In [67]:
# 서울 2024년 자료
df[(df.city=='서울')&(df.year==2024)] # and (X) boolean일때 괄호필수

  city  year   pop
2   서울  2024  0.92

## DataFrame 메서드

In [68]:
df

  city  year   pop
0   서울  2022  0.89
1   서울  2023  0.91
2   서울  2024  0.92
3  경기도  2022  1.10
4  경기도  2023  1.20
5  경기도  2024  1.15

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   city    6 non-null      object
 1   year    6 non-null      int64
 2   pop     6 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 276.0+ bytes

In [70]:
# 숫자타입(정수,실수)의 기술 통계량:
# non-null 데이터 개수, 평균, 표준편차, 최솟값, 1사 분위, 중앙값, 3사 분위, 최댓값 describe() 각각함수이름
df.describe()

              year       pop
count     6.000000  6.000000
mean   2023.000000  1.028333
std       0.894427  0.137320
min    2022.000000  0.890000
25%    2022.250000  0.912500
50%    2023.000000  1.010000
75%    2023.750000  1.137500
max    2024.000000  1.200000

In [71]:
#pop 컬럼의 평균
df['pop'].mean()

np.float64(1.0283333333333333)

In [72]:
df.city.value_counts() # 카테고리(범주) 타입의 데이터 기술 >> 빈도수. value_counts()

city
서울     3
경기도    3
Name: count, dtype: int64

In [73]:
df.head(n=3) #n의 기본값은 5 /// 앞에서 n개

  city  year   pop
0   서울  2022  0.89
1   서울  2023  0.91
2   서울  2024  0.92

In [74]:
df.tail(n=3) #n의 기본값은 5 /// 뒤에서 n개

  city  year   pop
3  경기도  2022  1.10
4  경기도  2023  1.20
5  경기도  2024  1.15

In [75]:
# 데이터프레임 df에서 pop컬럼의 값이 평균보다 큰 행들을 찾으세요
df['pop'].mean()

np.float64(1.0283333333333333)

In [76]:
df

  city  year   pop
0   서울  2022  0.89
1   서울  2023  0.91
2   서울  2024  0.92
3  경기도  2022  1.10
4  경기도  2023  1.20
5  경기도  2024  1.15

In [77]:
df[df['pop']>(df['pop'].mean())]
# select * from df where pop >avg(pop);

  city  year   pop
3  경기도  2022  1.10
4  경기도  2023  1.20
5  경기도  2024  1.15