In [2]:
import pandas as pd
import seaborn as sns

# 예제 데이터셋

In [3]:
#seaborn 패키지에서 제공하는 tips 데이터셋을 불러와서 DataFrame을 생성.
tips = sns.load_dataset('tips') #아규먼트는 문자열로

In [4]:
print(type(tips))

<class 'pandas.core.frame.DataFrame'>

In [5]:
tips.head() #DF의 첫 5개 행을 출력. tips.iloc(:5)와 같다.

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

# 연습문제


* DataFrame의 행과 열의 개수
* 열(column) 이름들
* 마지막 6개 행을 출력
* DataFrame의 요약 정보
* 숫자 타입 변수(컬럼)의 기술 통계량
* 카테고리 타입 변수의 빈도수
* total_bill 컬럼의 값이 최댓값인 행을 출력
* total_bill 컬럼의 값이 최솟값인 행을 출력
* 남성들의 tip의 평균
* 여성들의 tip의 평균
* 일요일의 tip의 평균
* 일요일 남성의 tip의 평균
* 일요일 여성의 tip의 평균

In [6]:
tips.shape
# (행의 갯수, 열의갯수)

(244, 7)

In [7]:
# tips.shape[0]
print('행의갯수 :',tips.shape[0])

행의갯수 : 244

In [8]:
# tips.shape[1]
print('열의갯수 :',tips.shape[1])

열의갯수 : 7

In [9]:
# tips.columns
for x in tips.columns:
  print(x) # Index 객체는 for-in 반복문사용가능

total_bill
tip
sex
smoker
day
time
size

In [10]:
# tips.tail(n=6)
tips.iloc[-6:]

     total_bill   tip     sex smoker   day    time  size
238       35.83  4.67  Female     No   Sat  Dinner     3
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [11]:
tips.info() # DF 요약정보

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [12]:
tips.describe() # 기술 통계량: non-null자료개수, 평균, 표준편차, 최소, 최대,...

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [13]:
#values_count            의미없음
tips.total_bill.value_counts()

total_bill
13.42    3
21.01    2
20.69    2
10.33    2
10.34    2
        ..
29.03    1
27.18    1
22.67    1
17.82    1
18.78    1
Name: count, Length: 229, dtype: int64

In [14]:
tips.tip.value_counts() # 의미없음

tip
2.00    33
3.00    23
4.00    12
2.50    10
5.00    10
        ..
1.47     1
1.17     1
4.67     1
5.92     1
1.75     1
Name: count, Length: 123, dtype: int64

In [15]:
tips.sex.value_counts() # 성별 빈도수

sex
Male      157
Female     87
Name: count, dtype: int64

In [16]:
tips.smoker.value_counts() # 흡연 여부 빈도수

smoker
No     151
Yes     93
Name: count, dtype: int64

In [17]:
tips.day.value_counts() # 요일 빈도수

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [18]:
tips.time.value_counts() # 시간 빈도수 카테고리타입(문자열) 4가지 info로 알수있음

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [19]:
# 인원수의 빈도수
tips['size'].value_counts()  # ? 이건 아닌듯 의미없음 size 메소드불가

size
2    156
3     38
4     37
5      5
1      4
6      4
Name: count, dtype: int64

* total_bill 컬럼의 값이 최댓값인 행을 출력
* total_bill 컬럼의 값이 최솟값인 행을 출력
* 남성들의 tip의 평균
* 여성들의 tip의 평균
* 일요일의 tip의 평균
* 일요일 남성의 tip의 평균
* 일요일 여성의 tip의 평균

In [20]:
tips['total_bill'].max()
# total_bill의 최댓값

50.81

In [21]:
tips['total_bill'].min()

3.07

In [22]:
tips[(tips['total_bill'])==(tips['total_bill'].max())]

     total_bill   tip   sex smoker  day    time  size
170       50.81  10.0  Male    Yes  Sat  Dinner     3

In [23]:
tips[(tips['total_bill'])==(tips['total_bill'].min())]

    total_bill  tip     sex smoker  day    time  size
67        3.07  1.0  Female    Yes  Sat  Dinner     1

In [24]:
tips[((tips['total_bill'])==tips['total_bill'].min())|
     ((tips['total_bill'])==tips['total_bill'].max())] # 줄바꿈 가능

     total_bill   tip     sex smoker  day    time  size
67         3.07   1.0  Female    Yes  Sat  Dinner     1
170       50.81  10.0    Male    Yes  Sat  Dinner     3

In [25]:
# tips.sex=='Male'  남성 팁의 평균
print(tips[(tips['sex']=='Male')].tip.mean())

3.0896178343949043

In [26]:
# 여성 팁의 평균
print(tips[(tips['sex']=='Female')].tip.mean())

2.8334482758620685

In [27]:
# tips
# tips[tips.day=='Sun']
# tips[tips.day=='Sun'].tip
# tips[tips.day=='Sun'].tip.mean()

In [28]:
# 일요일 팁 평균
print(tips[(tips['day']=='Sun')].tip.mean())

3.2551315789473687

In [29]:
# 일요일 남성 팁 평균
print(tips[(tips['day']=='Sun')&(tips['sex']=='Male')].tip.mean())

3.2203448275862065

In [30]:
# 일요일 여성 팁 평균
print(tips[(tips['day']=='Sun')&(tips['sex']=='Female')].tip.mean())

3.3672222222222223

In [31]:
# tip의 값이 평균보다 큰 행들을 찾으세요.
# select * from tips where tip > select avg(tip) from tips ;
tips[tips.tip>tips.tip.mean()]

     total_bill   tip     sex smoker   day    time  size
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
5         25.29  4.71    Male     No   Sun  Dinner     4
7         26.88  3.12    Male     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
232       11.61  3.39    Male     No   Sat  Dinner     2
234       15.53  3.00    Male    Yes   Sat  Dinner     2
238       35.83  4.67  Female     No   Sat  Dinner     3
239       29.03  5.92    Male     No   Sat  Dinner     3
243       18.78  3.00  Female     No  Thur  Dinner     2

[121 rows x 7 columns]

# 파생변수

In [32]:
tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [33]:
# 영수증 금액 대비 팁의 비율
(tips.tip / tips.total_bill)*100

0       5.944673
1      16.054159
2      16.658734
3      13.978041
4      14.680765
         ...
239    20.392697
240     7.358352
241     8.822232
242     9.820426
243    15.974441
Length: 244, dtype: float64

In [34]:
# 파생변수 추가
tips['tip_ratio']=(tips.tip/tips.total_bill)*100

In [35]:
tips.head()

   total_bill   tip     sex smoker  day    time  size  tip_ratio
0       16.99  1.01  Female     No  Sun  Dinner     2   5.944673
1       10.34  1.66    Male     No  Sun  Dinner     3  16.054159
2       21.01  3.50    Male     No  Sun  Dinner     3  16.658734
3       23.68  3.31    Male     No  Sun  Dinner     2  13.978041
4       24.59  3.61  Female     No  Sun  Dinner     4  14.680765

* 팁/영수증 비율의 평균값
* 팁/영수증 비율이 평균보다 큰 행들 찾기
* 팁/영수증 비율이 평균보다 큰 행들에서 남성/ 여성의 비율

In [36]:
print(tips.tip_ratio.mean())

16.08025817225047

In [37]:
tips.tip_ratio.describe()

count    244.000000
mean      16.080258
std        6.107220
min        3.563814
25%       12.912736
50%       15.476977
75%       19.147549
max       71.034483
Name: tip_ratio, dtype: float64

In [38]:
tips[tips['tip_ratio']>tips['tip_ratio'].mean()]

     total_bill   tip   sex smoker  day    time  size  tip_ratio
2         21.01  3.50  Male     No  Sun  Dinner     3  16.658734
5         25.29  4.71  Male     No  Sun  Dinner     4  18.623962
6          8.77  2.00  Male     No  Sun  Dinner     2  22.805017
9         14.78  3.23  Male     No  Sun  Dinner     2  21.853857
10        10.27  1.71  Male     No  Sun  Dinner     2  16.650438
..          ...   ...   ...    ...  ...     ...   ...        ...
228       13.28  2.72  Male     No  Sat  Dinner     2  20.481928
231       15.69  3.00  Male    Yes  Sat  Dinner     3  19.120459
232       11.61  3.39  Male     No  Sat  Dinner     2  29.198966
234       15.53  3.00  Male    Yes  Sat  Dinner     2  19.317450
239       29.03  5.92  Male     No  Sat  Dinner     3  20.392697

[107 rows x 8 columns]

In [39]:
biyul=tips[tips['tip_ratio']>tips['tip_ratio'].mean()]

In [40]:
# tips[tips['sex']=='Male'/tips['tip_ratio']>tips['tip_ratio'].mean()]
(biyul.sex.value_counts()/tips.sex.value_counts())*100

sex
Male      42.038217
Female    47.126437
Name: count, dtype: float64

In [41]:
# 전체 남성/여성 고객들 중에서 팁/영수증 비율이 평균보다 큰 남성/여성고객의 비율
# 위와같음

# TITANIC 데이터셋

In [42]:
titanic= sns.load_dataset('titanic')

In [43]:
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

titanic 데이터 프레임의 컬럼들:

*   survived: 생존여부(0=사망,1=생존) 중복되는데이터 삭제 하는게 좋다
      * alive 컬럼과 같은내용(no=사망, yes=생존)
*   pclass:   객실등급
      * class 컬럼과 같은내용(1=First, 2=Second, 3=Third)
*   sex:      성별(male/female)
*   who:      성인남성(man), 성인여성(woman), 어린이(child)
*   adult_male: 성인 남성 여부(True, False)
*   age:      나이
*   sibsp:    동승한 형제자매(sibling) 또는 배우자(spouses) 수
*   parch:    동승한 부모(parents) 또는 자녀(children) 수
*   alone:    동승자 여부(True=동승자 없음(혼자), False=동승자 있음(혼자가아님))
*   fare:     운임(탑승권 가격)

In [44]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [45]:
#deck은 널이많이서 안쓴는게좋다

## 카테고리(범주) {변수=컬럼} 분석

In [46]:
titanic.survived.value_counts() #생존여부

survived
0    549
1    342
Name: count, dtype: int64

In [47]:
titanic.alive.value_counts() # 문자를 숫자로 >> 데이터인코딩 ML시 유용한작업

alive
no     549
yes    342
Name: count, dtype: int64

In [48]:
titanic.sex.value_counts() # 성별 빈도수

sex
male      577
female    314
Name: count, dtype: int64

In [49]:
titanic.who.value_counts() # 성인남성/ 성인여성/ 어린이 빈도수

who
man      537
woman    271
child     83
Name: count, dtype: int64

In [50]:
titanic.adult_male.value_counts() # 성인남성 여부

adult_male
True     537
False    354
Name: count, dtype: int64

In [51]:
titanic.pclass.value_counts()

pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [52]:
titanic['class'].value_counts()

class
Third     491
First     216
Second    184
Name: count, dtype: int64

## 성인남성/성인여성/어린이 생존 비율

In [53]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [54]:
salda=titanic[titanic.alive=='yes'] #사망자그룹, 동승자, 운임료

In [55]:
titanic[titanic.alive=='yes']

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
875,1,3,female,15.0,0,0,7.2250,C,Third,child,False,NaN,Cherbourg,yes,True
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
880,1,2,female,25.0,0,1,26.0000,S,Second,woman,False,NaN,Southampton,yes,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True

In [56]:
titanic[titanic.survived==1]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
875,1,3,female,15.0,0,0,7.2250,C,Third,child,False,NaN,Cherbourg,yes,True
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
880,1,2,female,25.0,0,1,26.0000,S,Second,woman,False,NaN,Southampton,yes,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True

In [57]:
salda.who.value_counts() #생존자 성인남성/성인여성/어린이 숫자

who
woman    205
man       88
child     49
Name: count, dtype: int64

In [58]:
(salda.who.value_counts()/titanic.who.value_counts())*100 # 같은 인덱스끼리계산해줌

who
child    59.036145
man      16.387337
woman    75.645756
Name: count, dtype: float64

In [59]:
ss=salda.who.value_counts()

In [60]:
aa=titanic.who.value_counts()

In [80]:
(ss/aa)*100

who
child    59.036145
man      16.387337
woman    75.645756
Name: count, dtype: float64

## 객실 등급별 생존 비율

In [62]:
salda.pclass.value_counts() # 각 객실 등급의 생존자 숫자

pclass
1    136
3    119
2     87
Name: count, dtype: int64

In [63]:
salda['class'].value_counts()

class
First     136
Third     119
Second     87
Name: count, dtype: int64

In [64]:
titanic.pclass.value_counts()

pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [65]:
(salda['class'].value_counts()/titanic['class'].value_counts())*100

class
First     62.962963
Second    47.282609
Third     24.236253
Name: count, dtype: float64

In [66]:
(salda.pclass.value_counts()/titanic.pclass.value_counts())*100

pclass
1    62.962963
2    47.282609
3    24.236253
Name: count, dtype: float64

## 각 객실 등급에서 성인남성/성인여성/어린이 생존 비율

In [67]:
salda[['pclass','who']].value_counts()

pclass  who
1       woman    89
2       woman    60
3       woman    56
1       man      42
3       man      38
        child    25
2       child    19
        man       8
1       child     5
Name: count, dtype: int64

In [68]:
salda[['class','who']].value_counts() # 생존자 데이터 프레임에서 pclass, who컬럼 선택

class   who
First   woman    89
Second  woman    60
Third   woman    56
First   man      42
Third   man      38
        child    25
Second  child    19
        man       8
First   child     5
Name: count, dtype: int64

In [69]:
titanic[['pclass','who']].value_counts()

pclass  who
3       man      319
1       man      119
3       woman    114
2       man       99
1       woman     91
2       woman     66
3       child     58
2       child     19
1       child      6
Name: count, dtype: int64

In [70]:
(salda[['class','who']].value_counts()/titanic[['class','who']].value_counts())*100 # 생존자 데이터프레임에서 객실등급별, 성별(어린이포함) 빈도수

class   who
First   child     83.333333
        man       35.294118
        woman     97.802198
Second  child    100.000000
        man        8.080808
        woman     90.909091
Third   child     43.103448
        man       11.912226
        woman     49.122807
Name: count, dtype: float64

In [71]:
#사망자그룹, 동승자, 운임료
jukda=titanic[titanic.alive=='no']
jukda

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [72]:
jukda.pclass.value_counts()

pclass
3    372
2     97
1     80
Name: count, dtype: int64

In [73]:
salda[(salda['fare']==salda['fare'].max())|
      (salda['fare']==salda['fare'].min())]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
258,1,1,female,35.0,0,0,512.3292,C,First,woman,False,NaN,Cherbourg,yes,True
271,1,3,male,25.0,0,0,0.0000,S,Third,man,True,NaN,Southampton,yes,True
679,1,1,male,36.0,0,1,512.3292,C,First,man,True,B,Cherbourg,yes,False
737,1,1,male,35.0,0,0,512.3292,C,First,man,True,B,Cherbourg,yes,True

In [74]:
jukda[(jukda['fare'] == jukda['fare'].max())|
      (jukda['fare']==jukda['fare'].min())]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
27,0,1,male,19.0,3,2,263.0,S,First,man,True,C,Southampton,no,False
179,0,3,male,36.0,0,0,0.0,S,Third,man,True,NaN,Southampton,no,True
263,0,1,male,40.0,0,0,0.0,S,First,man,True,B,Southampton,no,True
277,0,2,male,NaN,0,0,0.0,S,Second,man,True,NaN,Southampton,no,True
302,0,3,male,19.0,0,0,0.0,S,Third,man,True,NaN,Southampton,no,True
413,0,2,male,NaN,0,0,0.0,S,Second,man,True,NaN,Southampton,no,True
438,0,1,male,64.0,1,4,263.0,S,First,man,True,C,Southampton,no,False
466,0,2,male,NaN,0,0,0.0,S,Second,man,True,NaN,Southampton,no,True
481,0,2,male,NaN,0,0,0.0,S,Second,man,True,NaN,Southampton,no,True
597,0,3,male,49.0,0,0,0.0,S,Third,man,True,NaN,Southampton,no,True
633,0,1,male,NaN,0,0,0.0,S,First,man,True,NaN,Southampton,no,True
674,0,2,male,NaN,0,0,0.0,S,Second,man,True,NaN,Southampton,no,True
732,0,2,male,NaN,0,0,0.0,S,Second,man,True,NaN,Southampton,no,True
806,0,1,male,39.0,0,0,0.0,S,First,man,True,A,Southampton,no,True
815,0,1,male,NaN,0,0,0.0,S,First,man,True,B,Southampton,no,True
822,0,1,male,38.0,0,0,0.0,S,First,man,True,NaN,Southampton,no,True

In [75]:
(jukda[['class','who']].value_counts()/titanic[['class','who']].value_counts())*100 # 안죽으면 nan

class   who
First   child    16.666667
        man      64.705882
        woman     2.197802
Second  child          NaN
        man      91.919192
        woman     9.090909
Third   child    56.896552
        man      88.087774
        woman    50.877193
Name: count, dtype: float64

In [76]:
#동승자 유무에 따른 생존자비율
#운임료에 따른 생존자비율
hapsuck=titanic[titanic.alone==True]
hapsuck

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [77]:
# hapsuck[hapsuck['alive'].value_counts()/((hapsuck['alive']=='yes').sum()+(hapsuck['alive']=='no').sum())]
(hapsuck['alive'] == 'yes').sum() / len(hapsuck)

np.float64(0.30353817504655495)

In [78]:
(salda[['alone','who']].value_counts()/ titanic[['alone','who']].value_counts())*100

alone  who
False  child    58.441558
       man      18.897638
       woman    73.333333
True   child    66.666667
       man      15.609756
       woman    78.512397
Name: count, dtype: float64

In [79]:
(salda[['embark_town','who']].value_counts()/titanic[['embark_town','who']].value_counts())*100

embark_town  who
Cherbourg    child    77.777778
             man      28.888889
             woman    88.333333
Queenstown   child    20.000000
             man       8.108108
             woman    74.285714
Southampton  child    56.666667
             man      14.390244
             woman    71.264368
Name: count, dtype: float64