# 파일을 읽어서 DataFrame을 생성하기

*   txt
*   csv(comma-seperated values), tsv(tap-seperated values)
*   xls, xlsx

In [1]:
import pandas as pd

# csv 파일의 첫번째 행이 컬럼 이름인 경우

In [2]:
# github에 저장된 CSV 파일 경로
ex1_path='https://raw.githubusercontent.com/wesm/pydata-book/refs/heads/3rd-edition/examples/ex1.csv'

In [5]:
ex1_df=pd.read_csv(ex1_path)

In [7]:
ex1_df

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [8]:
ex1_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   a        3 non-null      int64
 1   b        3 non-null      int64
 2   c        3 non-null      int64
 3   d        3 non-null      int64
 4   message  3 non-null      object
dtypes: int64(4), object(1)
memory usage: 252.0+ bytes

# CSV 파일의 첫번째 행부터 데이터인 경우

컬럼 이름이 파일에 없는 경우

In [9]:
ex2_path='https://raw.githubusercontent.com/wesm/pydata-book/refs/heads/3rd-edition/examples/ex2.csv'

In [12]:
ex2_df=pd.read_csv(ex2_path, names=['col1','col2','col3','col4','col5'])

In [13]:
ex2_df # 컬럼으로 올라가 버림 names를만들면 거기적힌게 컬럼이됨

   col1  col2  col3  col4   col5
0     1     2     3     4  hello
1     5     6     7     8  world
2     9    10    11    12    foo

In [14]:
ex2_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    3 non-null      int64
 1   col2    3 non-null      int64
 2   col3    3 non-null      int64
 3   col4    3 non-null      int64
 4   col5    3 non-null      object
dtypes: int64(4), object(1)
memory usage: 252.0+ bytes

`read_csv()` 함수의 names 파라미터는 DataFrame의 컬럼 이름을 설정할 때 사용.

*   CSV 파일에 컬럼 이름이 없는 경우
*   CSV 파일에 컬럼 이름이 있지만, 컬럼 이름을 재지정할 때

In [20]:
ex1_df=pd.read_csv(ex1_path, names=['korean','english','math','science','message'],
                   header=0) # 파일의 첫번째 라인은 데이터가 아니라 헤더임을 알려줌.

In [21]:
ex1_df

   korean  english  math  science message
0       1        2     3        4   hello
1       5        6     7        8   world
2       9       10    11       12     foo

In [22]:
ex1_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   korean   3 non-null      int64
 1   english  3 non-null      int64
 2   math     3 non-null      int64
 3   science  3 non-null      int64
 4   message  3 non-null      object
dtypes: int64(4), object(1)
memory usage: 252.0+ bytes

# 값들이 공백으로 구분된 텍스트 파일(txt, csv, tsv, ...)

In [23]:
ex3_path='https://raw.githubusercontent.com/wesm/pydata-book/refs/heads/3rd-edition/examples/ex3.txt'

In [49]:
ex3_df=pd.read_csv(ex3_path,sep='\\s+')# 여러개의공백으로 나
# ex3_df=pd.read_csv(ex3_path,sep='\t')

In [50]:
ex3_df

            A         B         C
aaa -0.264438 -1.026059 -0.619500
bbb  0.927272  0.302904 -0.032399
ccc -0.264273 -0.386314 -0.217601
ddd -0.871858 -0.348382  1.100491

In [27]:
ex3_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, aaa to ddd
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       4 non-null      float64
 1   B       4 non-null      float64
 2   C       4 non-null      float64
dtypes: float64(3)
memory usage: 300.0+ bytes

ex3.txt 파일은 컬럼 이름과 행 인덱스를 가지고 있는 형식.

In [33]:
ex3_df.loc['aaa']

A   -0.264438
B   -1.026059
C   -0.619500
Name: aaa, dtype: float64

In [35]:
ex3_df.iloc[0]

A   -0.264438
B   -1.026059
C   -0.619500
Name: aaa, dtype: float64

In [37]:
ex3_df.loc['aaa':'bbb']

            A         B         C
aaa -0.264438 -1.026059 -0.619500
bbb  0.927272  0.302904 -0.032399

In [38]:
ex3_df.iloc[0:2]

            A         B         C
aaa -0.264438 -1.026059 -0.619500
bbb  0.927272  0.302904 -0.032399

# 컬럼 헤더(이름)와 데이터 이외의 주석등을 포함하는 파일

In [39]:
ex4_path='https://raw.githubusercontent.com/wesm/pydata-book/refs/heads/3rd-edition/examples/ex4.csv'

In [43]:
ex4_df=pd.read_csv(ex4_path,skiprows=[0,2,3])
ex4_df

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

*   csv(txt) 파일 >>> DataFrame: `pq.read_csv()` 함수사용.
*   DataFrame >>> csv 파일 저장: `pd.DataFrame.to_csv()` 메서드 사용.

In [46]:
# ex3_df를 ex3.csv 파일로 저장
ex3_df.to_csv('ex3.csv')

In [48]:
# ex4_df를 ex4.csv 파일로 저장
ex4_df.to_csv('ex4.csv',index=False)

# 엑셀 파일 읽기

In [51]:
file_path='https://github.com/wesm/pydata-book/raw/refs/heads/3rd-edition/examples/ex1.xlsx'

In [52]:
excel_df=pd.read_excel(file_path)

In [53]:
excel_df

   Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo

In [54]:
excel_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  3 non-null      int64
 1   a           3 non-null      int64
 2   b           3 non-null      int64
 3   c           3 non-null      int64
 4   d           3 non-null      int64
 5   message     3 non-null      object
dtypes: int64(5), object(1)
memory usage: 276.0+ bytes

In [55]:
excel_df2=pd.read_excel(file_path, index_col=0)

In [56]:
excel_df2

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo