# Categorical Data 다루기

In [2]:
import numpy as np
import pandas as pd

In [3]:
df=pd.DataFrame(data={
    'user_id':np.arange(1,11),
    'gender':['M']*5+['F']*5,
    'score':np.random.randint(1,6,size=10)
})

In [4]:
df

   user_id gender  score
0        1      M      2
1        2      M      1
2        3      M      4
3        4      M      5
4        5      M      4
5        6      F      2
6        7      F      2
7        8      F      4
8        9      F      4
9       10      F      4

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   user_id  10 non-null     int64
 1   gender   10 non-null     object
 2   score    10 non-null     int64
dtypes: int64(2), object(1)
memory usage: 372.0+ bytes

# 연속형변수에서 파생변수 만들기

In [6]:
# gender 컬럼을 문자열 타입에서 카테고리 타입으로 변환.
df.gender=df.gender.astype('category')

In [7]:
df.gender

0    M
1    M
2    M
3    M
4    M
5    F
6    F
7    F
8    F
9    F
Name: gender, dtype: category
Categories (2, object): ['F', 'M']

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   user_id  10 non-null     int64
 1   gender   10 non-null     category
 2   score    10 non-null     int64
dtypes: category(1), int64(2)
memory usage: 426.0 bytes

In [9]:
# Category Accessor(카테고리 접근자)
df.gender.cat.categories

Index(['F', 'M'], dtype='object')

# 연속형 변수에서 파생된 카테고리 변수 만들기

In [10]:
df= pd.DataFrame(data={
    'id':np.arange(1,11),
    'age':np.random.randint(100,size=10)
})

In [11]:
df

   id  age
0   1   98
1   2   16
2   3   26
3   4   63
4   5   58
5   6   87
6   7   92
7   8   71
8   9   59
9  10   40

In [13]:
# age 컬럼의 값을 이용해서 연령대 파생변수를 추가.
df['age_range']=pd.cut(x=df.age,bins=np.arange(0, 110, 10),right=False)#x=data,    0부터100 까지 10씩, right False[)   True(]

In [28]:
df

   id  age  age_range
0   1   99  [90, 100)
1   2   61   [60, 70)
2   3    8    [0, 10)
3   4   38   [30, 40)
4   5   56   [50, 60)
5   6   77   [70, 80)
6   7   12   [10, 20)
7   8    9    [0, 10)
8   9   45   [40, 50)
9  10   72   [70, 80)

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         10 non-null     int64
 1   age        10 non-null     int64
 2   age_range  10 non-null     category
dtypes: category(1), int64(2)
memory usage: 762.0 bytes

In [30]:
df.age_range.cat.categories

IntervalIndex([  [0, 10),  [10, 20),  [20, 30),  [30, 40),  [40, 50),
                [50, 60),  [60, 70),  [70, 80),  [80, 90), [90, 100)],
              dtype='interval[int64, left]')

In [31]:
# age 컬럼의 값을 사용한 파생변수
df['age_cat']=pd.cut(x=df.age,bins=[0,19,45,60,100],right=False,
                     labels=['미성년자','청년','장년','노년'])

In [32]:
df

   id  age  age_range age_cat
0   1   99  [90, 100)      노년
1   2   61   [60, 70)      노년
2   3    8    [0, 10)    미성년자
3   4   38   [30, 40)      청년
4   5   56   [50, 60)      장년
5   6   77   [70, 80)      노년
6   7   12   [10, 20)    미성년자
7   8    9    [0, 10)    미성년자
8   9   45   [40, 50)      장년
9  10   72   [70, 80)      노년

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         10 non-null     int64
 1   age        10 non-null     int64
 2   age_range  10 non-null     category
 3   age_cat    10 non-null     category
dtypes: category(2), int64(2)
memory usage: 976.0 bytes

In [35]:
df.age_cat.cat.categories

Index(['미성년자', '청년', '장년', '노년'], dtype='object')